### PR TITLE
Add UUID type

### PR DESCRIPTION
**Pull request by OussamaRomdhane**

### CODE REVIEW

**Comment by wzrdtales** [comment]
non standard, not shared. this is only applicable on driver level not for all drivers.

**Comment by OussamaRomdhane** [comment]
Thank you, that makes sense. I'm not very familiar with how you handle types internally but is there a way to extend this in https://github.com/db-migrate/pg (I mean is it worth pursuing if I want to push for the change?)

Or is it also not recommendable since it relies on an extension?

**Comment by wzrdtales** [comment]
https://github.com/db-migrate/pg/blob/49f3848d921e3a6dde2630cbc318a6652e75d8f2/index.js#L76

**Comment by OussamaRomdhane** [comment]
🙏 Thank you, I'll open a PR there

**Pull request closed without merging**
